# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    slack(message: "빌드시작",channel: "#ios",
     slack_url: "https://hooks.slack.com/services/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")

    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    # build_app(workspace: "ZIP_ios.xcworkspace",
    #  scheme: "ZIP_ios",
    #  include_bitcode: false)

     gym(scheme: "ZIP_ios",
      output_directory: "fastlane/ipa/",
      workspace: "ZIP_ios.xcworkspace",
      include_bitcode: false,
      xcargs: "-allowProvisioningUpdates",
      silent: true,
        clean: true) # Build your app - more options available
    upload_to_testflight
    slack(message: "테스트 플라이트 배포 완료",channel: "#ios",
     slack_url: "https://hooks.slack.com/services/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")
    increment_build_number(build_number: latest_testflight_build_number + 1,
      xcodeproj: "ZIP_ios.xcodeproj")
  end





  lane :tests do
  	slack(message: "App successfully released!",channel: "#ios",
  	 slack_url: "https://hooks.slack.com/services/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")
  end
end
